apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: longhorn-system
spec:
  nodeSelector:
    kubernetes.io/hostname: 172.31.17.195
  containers:
  - name: volume-test
    image: jacie/mytest:pod
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command: ["go", "run", "mytest.go"]
    args: ["--testetcd=true", "--testk8s=false", "--certFile=/etc/kubernetes/ssl/kube-etcd-172-31-17-195.pem", "--keyFile=/etc/kubernetes/ssl/kube-etcd-172-31-17-195-key.pem", "--endpoints=172.31.17.195:2379"]
    volumeMounts:
      - name: ssl
        mountPath: /etc/kubernetes/ssl
  serviceAccountName: longhorn-service-account
  volumes:
    - name: ssl
      hostPath:
        path: /etc/kubernetes/ssl